// Generated by gencpp from file from2Dto3D/PointBaseResponse.msg
// DO NOT EDIT!


#ifndef FROM2DTO3D_MESSAGE_POINTBASERESPONSE_H
#define FROM2DTO3D_MESSAGE_POINTBASERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace from2Dto3D
{
template <class ContainerAllocator>
struct PointBaseResponse_
{
  typedef PointBaseResponse_<ContainerAllocator> Type;

  PointBaseResponse_()
    : pose()  {
    }
  PointBaseResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PointBaseResponse_

typedef ::from2Dto3D::PointBaseResponse_<std::allocator<void> > PointBaseResponse;

typedef boost::shared_ptr< ::from2Dto3D::PointBaseResponse > PointBaseResponsePtr;
typedef boost::shared_ptr< ::from2Dto3D::PointBaseResponse const> PointBaseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::from2Dto3D::PointBaseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace from2Dto3D

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d562f95ca92089ed9ca118a23535a58f";
  }

  static const char* value(const ::from2Dto3D::PointBaseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd562f95ca92089edULL;
  static const uint64_t static_value2 = 0x9ca118a23535a58fULL;
};

template<class ContainerAllocator>
struct DataType< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "from2Dto3D/PointBaseResponse";
  }

  static const char* value(const ::from2Dto3D::PointBaseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::from2Dto3D::PointBaseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointBaseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::from2Dto3D::PointBaseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::from2Dto3D::PointBaseResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FROM2DTO3D_MESSAGE_POINTBASERESPONSE_H
