// Generated by gencpp from file tf_lookup/lookupTransform.msg
// DO NOT EDIT!


#ifndef TF_LOOKUP_MESSAGE_LOOKUPTRANSFORM_H
#define TF_LOOKUP_MESSAGE_LOOKUPTRANSFORM_H

#include <ros/service_traits.h>


#include <tf_lookup/lookupTransformRequest.h>
#include <tf_lookup/lookupTransformResponse.h>


namespace tf_lookup
{

struct lookupTransform
{

typedef lookupTransformRequest Request;
typedef lookupTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lookupTransform
} // namespace tf_lookup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_lookup::lookupTransform > {
  static const char* value()
  {
    return "02c6b9366a79d71ff07f2dc56c230415";
  }

  static const char* value(const ::tf_lookup::lookupTransform&) { return value(); }
};

template<>
struct DataType< ::tf_lookup::lookupTransform > {
  static const char* value()
  {
    return "tf_lookup/lookupTransform";
  }

  static const char* value(const ::tf_lookup::lookupTransform&) { return value(); }
};


// service_traits::MD5Sum< ::tf_lookup::lookupTransformRequest> should match 
// service_traits::MD5Sum< ::tf_lookup::lookupTransform > 
template<>
struct MD5Sum< ::tf_lookup::lookupTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_lookup::lookupTransform >::value();
  }
  static const char* value(const ::tf_lookup::lookupTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_lookup::lookupTransformRequest> should match 
// service_traits::DataType< ::tf_lookup::lookupTransform > 
template<>
struct DataType< ::tf_lookup::lookupTransformRequest>
{
  static const char* value()
  {
    return DataType< ::tf_lookup::lookupTransform >::value();
  }
  static const char* value(const ::tf_lookup::lookupTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_lookup::lookupTransformResponse> should match 
// service_traits::MD5Sum< ::tf_lookup::lookupTransform > 
template<>
struct MD5Sum< ::tf_lookup::lookupTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_lookup::lookupTransform >::value();
  }
  static const char* value(const ::tf_lookup::lookupTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_lookup::lookupTransformResponse> should match 
// service_traits::DataType< ::tf_lookup::lookupTransform > 
template<>
struct DataType< ::tf_lookup::lookupTransformResponse>
{
  static const char* value()
  {
    return DataType< ::tf_lookup::lookupTransform >::value();
  }
  static const char* value(const ::tf_lookup::lookupTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_LOOKUP_MESSAGE_LOOKUPTRANSFORM_H
