// Generated by gencpp from file from2Dto3D/reachpointResponse.msg
// DO NOT EDIT!


#ifndef FROM2DTO3D_MESSAGE_REACHPOINTRESPONSE_H
#define FROM2DTO3D_MESSAGE_REACHPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace from2Dto3D
{
template <class ContainerAllocator>
struct reachpointResponse_
{
  typedef reachpointResponse_<ContainerAllocator> Type;

  reachpointResponse_()
    : res(false)  {
    }
  reachpointResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::from2Dto3D::reachpointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::from2Dto3D::reachpointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct reachpointResponse_

typedef ::from2Dto3D::reachpointResponse_<std::allocator<void> > reachpointResponse;

typedef boost::shared_ptr< ::from2Dto3D::reachpointResponse > reachpointResponsePtr;
typedef boost::shared_ptr< ::from2Dto3D::reachpointResponse const> reachpointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::from2Dto3D::reachpointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace from2Dto3D

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::from2Dto3D::reachpointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::from2Dto3D::reachpointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::from2Dto3D::reachpointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::from2Dto3D::reachpointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "from2Dto3D/reachpointResponse";
  }

  static const char* value(const ::from2Dto3D::reachpointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool res\n\
";
  }

  static const char* value(const ::from2Dto3D::reachpointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reachpointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::from2Dto3D::reachpointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::from2Dto3D::reachpointResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FROM2DTO3D_MESSAGE_REACHPOINTRESPONSE_H
