// Generated by gencpp from file tf_tiago/doorshaftRequest.msg
// DO NOT EDIT!


#ifndef TF_TIAGO_MESSAGE_DOORSHAFTREQUEST_H
#define TF_TIAGO_MESSAGE_DOORSHAFTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tf_tiago
{
template <class ContainerAllocator>
struct doorshaftRequest_
{
  typedef doorshaftRequest_<ContainerAllocator> Type;

  doorshaftRequest_()
    : doorshaft_req()
    , theta(0.0)  {
    }
  doorshaftRequest_(const ContainerAllocator& _alloc)
    : doorshaft_req(_alloc)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _doorshaft_req_type;
  _doorshaft_req_type doorshaft_req;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::tf_tiago::doorshaftRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_tiago::doorshaftRequest_<ContainerAllocator> const> ConstPtr;

}; // struct doorshaftRequest_

typedef ::tf_tiago::doorshaftRequest_<std::allocator<void> > doorshaftRequest;

typedef boost::shared_ptr< ::tf_tiago::doorshaftRequest > doorshaftRequestPtr;
typedef boost::shared_ptr< ::tf_tiago::doorshaftRequest const> doorshaftRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_tiago::doorshaftRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tf_tiago

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_tiago::doorshaftRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_tiago::doorshaftRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_tiago::doorshaftRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b8aa83513f12fb8b56fc4c3ee3f800f";
  }

  static const char* value(const ::tf_tiago::doorshaftRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b8aa83513f12fb8ULL;
  static const uint64_t static_value2 = 0xb56fc4c3ee3f800fULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_tiago/doorshaftRequest";
  }

  static const char* value(const ::tf_tiago::doorshaftRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point doorshaft_req\n\
float64  theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::tf_tiago::doorshaftRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.doorshaft_req);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct doorshaftRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_tiago::doorshaftRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_tiago::doorshaftRequest_<ContainerAllocator>& v)
  {
    s << indent << "doorshaft_req: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.doorshaft_req);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_TIAGO_MESSAGE_DOORSHAFTREQUEST_H
