// Generated by gencpp from file tf_tiago/doorshaft.msg
// DO NOT EDIT!


#ifndef TF_TIAGO_MESSAGE_DOORSHAFT_H
#define TF_TIAGO_MESSAGE_DOORSHAFT_H

#include <ros/service_traits.h>


#include <tf_tiago/doorshaftRequest.h>
#include <tf_tiago/doorshaftResponse.h>


namespace tf_tiago
{

struct doorshaft
{

typedef doorshaftRequest Request;
typedef doorshaftResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct doorshaft
} // namespace tf_tiago


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_tiago::doorshaft > {
  static const char* value()
  {
    return "1f18b22190848c43ce6dd74d4ba3de60";
  }

  static const char* value(const ::tf_tiago::doorshaft&) { return value(); }
};

template<>
struct DataType< ::tf_tiago::doorshaft > {
  static const char* value()
  {
    return "tf_tiago/doorshaft";
  }

  static const char* value(const ::tf_tiago::doorshaft&) { return value(); }
};


// service_traits::MD5Sum< ::tf_tiago::doorshaftRequest> should match 
// service_traits::MD5Sum< ::tf_tiago::doorshaft > 
template<>
struct MD5Sum< ::tf_tiago::doorshaftRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_tiago::doorshaft >::value();
  }
  static const char* value(const ::tf_tiago::doorshaftRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_tiago::doorshaftRequest> should match 
// service_traits::DataType< ::tf_tiago::doorshaft > 
template<>
struct DataType< ::tf_tiago::doorshaftRequest>
{
  static const char* value()
  {
    return DataType< ::tf_tiago::doorshaft >::value();
  }
  static const char* value(const ::tf_tiago::doorshaftRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_tiago::doorshaftResponse> should match 
// service_traits::MD5Sum< ::tf_tiago::doorshaft > 
template<>
struct MD5Sum< ::tf_tiago::doorshaftResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_tiago::doorshaft >::value();
  }
  static const char* value(const ::tf_tiago::doorshaftResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_tiago::doorshaftResponse> should match 
// service_traits::DataType< ::tf_tiago::doorshaft > 
template<>
struct DataType< ::tf_tiago::doorshaftResponse>
{
  static const char* value()
  {
    return DataType< ::tf_tiago::doorshaft >::value();
  }
  static const char* value(const ::tf_tiago::doorshaftResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_TIAGO_MESSAGE_DOORSHAFT_H
