// Generated by gencpp from file tf_tiago/gripper.msg
// DO NOT EDIT!


#ifndef TF_TIAGO_MESSAGE_GRIPPER_H
#define TF_TIAGO_MESSAGE_GRIPPER_H

#include <ros/service_traits.h>


#include <tf_tiago/gripperRequest.h>
#include <tf_tiago/gripperResponse.h>


namespace tf_tiago
{

struct gripper
{

typedef gripperRequest Request;
typedef gripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gripper
} // namespace tf_tiago


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_tiago::gripper > {
  static const char* value()
  {
    return "6f30bda2019fa1b00d58178314aa1769";
  }

  static const char* value(const ::tf_tiago::gripper&) { return value(); }
};

template<>
struct DataType< ::tf_tiago::gripper > {
  static const char* value()
  {
    return "tf_tiago/gripper";
  }

  static const char* value(const ::tf_tiago::gripper&) { return value(); }
};


// service_traits::MD5Sum< ::tf_tiago::gripperRequest> should match 
// service_traits::MD5Sum< ::tf_tiago::gripper > 
template<>
struct MD5Sum< ::tf_tiago::gripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_tiago::gripper >::value();
  }
  static const char* value(const ::tf_tiago::gripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_tiago::gripperRequest> should match 
// service_traits::DataType< ::tf_tiago::gripper > 
template<>
struct DataType< ::tf_tiago::gripperRequest>
{
  static const char* value()
  {
    return DataType< ::tf_tiago::gripper >::value();
  }
  static const char* value(const ::tf_tiago::gripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_tiago::gripperResponse> should match 
// service_traits::MD5Sum< ::tf_tiago::gripper > 
template<>
struct MD5Sum< ::tf_tiago::gripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_tiago::gripper >::value();
  }
  static const char* value(const ::tf_tiago::gripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_tiago::gripperResponse> should match 
// service_traits::DataType< ::tf_tiago::gripper > 
template<>
struct DataType< ::tf_tiago::gripperResponse>
{
  static const char* value()
  {
    return DataType< ::tf_tiago::gripper >::value();
  }
  static const char* value(const ::tf_tiago::gripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_TIAGO_MESSAGE_GRIPPER_H
