// Generated by gencpp from file tf_tiago/gripperRequest.msg
// DO NOT EDIT!


#ifndef TF_TIAGO_MESSAGE_GRIPPERREQUEST_H
#define TF_TIAGO_MESSAGE_GRIPPERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace tf_tiago
{
template <class ContainerAllocator>
struct gripperRequest_
{
  typedef gripperRequest_<ContainerAllocator> Type;

  gripperRequest_()
    : gripper_req()  {
    }
  gripperRequest_(const ContainerAllocator& _alloc)
    : gripper_req(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Twist_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Twist_<ContainerAllocator> >::other >  _gripper_req_type;
  _gripper_req_type gripper_req;





  typedef boost::shared_ptr< ::tf_tiago::gripperRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_tiago::gripperRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gripperRequest_

typedef ::tf_tiago::gripperRequest_<std::allocator<void> > gripperRequest;

typedef boost::shared_ptr< ::tf_tiago::gripperRequest > gripperRequestPtr;
typedef boost::shared_ptr< ::tf_tiago::gripperRequest const> gripperRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_tiago::gripperRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_tiago::gripperRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tf_tiago

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tf_tiago::gripperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_tiago::gripperRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_tiago::gripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_tiago::gripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_tiago::gripperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_tiago::gripperRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_tiago::gripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18164dd6ebe032f6a582a1eda787dad4";
  }

  static const char* value(const ::tf_tiago::gripperRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18164dd6ebe032f6ULL;
  static const uint64_t static_value2 = 0xa582a1eda787dad4ULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_tiago::gripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_tiago/gripperRequest";
  }

  static const char* value(const ::tf_tiago::gripperRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_tiago::gripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist[] gripper_req\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::tf_tiago::gripperRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_tiago::gripperRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripperRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_tiago::gripperRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_tiago::gripperRequest_<ContainerAllocator>& v)
  {
    s << indent << "gripper_req[]" << std::endl;
    for (size_t i = 0; i < v.gripper_req.size(); ++i)
    {
      s << indent << "  gripper_req[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "    ", v.gripper_req[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_TIAGO_MESSAGE_GRIPPERREQUEST_H
