// Generated by gencpp from file tf_tiago/ReachGoalResponse.msg
// DO NOT EDIT!


#ifndef TF_TIAGO_MESSAGE_REACHGOALRESPONSE_H
#define TF_TIAGO_MESSAGE_REACHGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tf_tiago
{
template <class ContainerAllocator>
struct ReachGoalResponse_
{
  typedef ReachGoalResponse_<ContainerAllocator> Type;

  ReachGoalResponse_()
    : reach(false)  {
    }
  ReachGoalResponse_(const ContainerAllocator& _alloc)
    : reach(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reach_type;
  _reach_type reach;





  typedef boost::shared_ptr< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReachGoalResponse_

typedef ::tf_tiago::ReachGoalResponse_<std::allocator<void> > ReachGoalResponse;

typedef boost::shared_ptr< ::tf_tiago::ReachGoalResponse > ReachGoalResponsePtr;
typedef boost::shared_ptr< ::tf_tiago::ReachGoalResponse const> ReachGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_tiago::ReachGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tf_tiago

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e28478de0c42bf45c139fda1fb68c47f";
  }

  static const char* value(const ::tf_tiago::ReachGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe28478de0c42bf45ULL;
  static const uint64_t static_value2 = 0xc139fda1fb68c47fULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_tiago/ReachGoalResponse";
  }

  static const char* value(const ::tf_tiago::ReachGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reach\n\
";
  }

  static const char* value(const ::tf_tiago::ReachGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reach);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReachGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_tiago::ReachGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_tiago::ReachGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "reach: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reach);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_TIAGO_MESSAGE_REACHGOALRESPONSE_H
